import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Goathouse</title>
        <meta name="description" content="Generated by create next app blog page for GoatHouse" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <div> 
          <img src="logo with text.png" height="300px" width="300px" />  
        </div>

        <p className={styles.description}>Explore the many great artist of GoatHouse</p>

        {/* card block for artist */}
        <div className={styles.grid}>
      
          <Link href="/artists/andrelle">
          <a href="/pages/artists/andrelle.js" className={styles.card}>
            <h2>Andrelle &rarr;</h2>
            <p>The first lady of the house
            <Image src="/andrelle/andrelle1.jpg" height="300px" width="250px" layout="fixed"/>
            </p>
          </a>
          </Link>

          <Link href="/artists/eryk">
          <a href="/pages/artists/eryck.js" className={styles.card}>
            <h2>Eryck &rarr;</h2>
            <p>conscious rapper
            <Image src="/eryk/eryk1.jpg" height="300px" width="250px" layout="fixed"/>
            </p>
          </a>
          </Link>

          <Link href="/artists/nyck">
          <a href="/pages/artists/nyck.js" className={styles.card}>
            <h2>Nyck &rarr;</h2>
            <p>producer & rapper
            <Image src="/nyck/nyck1.jpg" height="300px" width="250px" layout="fixed"/>
            </p>
          </a>
          </Link>

          <Link href="/artists/josh">
          <a href="/pages/artists/josh.js" className={styles.card}>
            <h2>Josh &rarr;</h2>
            <p>artist singer rapper
            <Image src="/josh/josh1.jpg" height="300px" width="250px" layout="fixed"/>
            </p>
          </a>
          </Link>

          {/* Latest project image of cover art onClick() => popup with link options to project */}
          <div>
            <a href="/latest">Check out GoatHouse's Latest Project</a>
          </div>
          
          
          

         
        </div>
      </main>
    </div>
  )
}
