import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Goathouse</title>
        <meta name="description" content="Generated by create next app blog page for GoatHouse" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Goathouse</h1>

        <p className={styles.description}>Explore the many great artist of GoatHouse</p>

        {/* card block for artist */}
        <div className={styles.grid}>
          
          <a href="https://open.spotify.com/artist/69JhM2SHl8MwHV9kBaKpzd?si=HeGnRoVOSNykuA3BXevKFg" className={styles.card}>
            <h2>Joel The Eagle &rarr;</h2>
            <p>Find out more about our Singer!
            <Image src="/woman.jpg" alt="woman standing" height="200px" width="200px" layout="fixed"/>
            </p>
          </a>
          
          <a href="https://open.spotify.com/artist/1XNA8x0dHXWG5XgpryKMU6?si=bjarDeGuSJms7tCNR_Escg" className={styles.card}>
            <h2>Andrelle &rarr;</h2>
            <p>Learn about the first lady of the house!
            <Image src="/woman.jpg" alt="woman standing" height="200px" width="200px" layout="fixed"/>
            </p>
          </a>

         
        </div>
      </main>
    </div>
  )
}
